#!/bin/bash

#go to the user's home directory
cd ~

#ensure that they have a bin directory
#mkdir bin

#go into it
#cd bin

#clone Orynx there
#git clone https://github.com/humannum14916/Orynx.git

#move the orynx bash script wrapper out
#of the Orynx directory and into bin
mv ~/bin/Orynx/orynx ~/bin
