#!/bin/bash

#install targets
mainDest="~/bin"
scriptDest="~/bin"

#go to the main install directory
cd "$mainDest"

#clone Orynx there
git clone https://github.com/humannum14916/Orynx.git

#rename the code directory from Orynx to OrynxCore
#(to prevent there being two files with the same name)
mv ~/bin/Orynx ~/bin/OrynxCore

#go to the script install directory
cd "$scriptDest"

#create a symlink to the wrapper script
ln -s "$scriptDest"/OrynxCore/orynx orynx
